### ISSUE TITLE
Crash when trying to view related anime

### ISSUE THREAD

**Issue by brendanny** [axiel7/AniHyou-android#67]
**Describe the bug (required)**
Crash when trying to view related anime. 

**To Reproduce**
1. Open anime (specifically Mushi-shi)
2. Click on the crossing arrows to try to view related anime
3. Crash

**Expected behavior**
N/A

**Screenshots**

**Enviroment (required)**
 - Device model: Pixel 8
 - Android version: 14
 - App version: 1.2.2

**Additional context (optional)**
Crash log:
```
type: crash
osVersion: google/shiba/shiba:14/UD1A.231105.004/2023112900:user/release-keys
package: com.axiel7.anihyou:43
process: com.axiel7.anihyou
processUptime: 2803 + 325 ms
installer: dev.imranr.obtainium

java.lang.IndexOutOfBoundsException: Index 2, size 2
	at z.t0.b(SourceFile:27)
	at z.t0.c(SourceFile:1)
	at q7.e.R(SourceFile:5)
	at x.o.b(SourceFile:11)
	at x.u.a(SourceFile:7)
	at x.v.n(SourceFile:1291)
	at t.q0.n(SourceFile:200)
	at t1.h0.b(SourceFile:74)
	at v1.u.a(SourceFile:82)
	at s.m.a(SourceFile:9)
	at s.m.m(SourceFile:14)
	at t1.b0.e(SourceFile:8)
	at v1.u.a(SourceFile:30)
	at s.m.a(SourceFile:38)
	at s.m.m(SourceFile:27)
	at t1.b0.e(SourceFile:8)
	at v1.u.a(SourceFile:30)
	at g1.t0.e(SourceFile:1)
	at v1.u.a(SourceFile:30)
	at w.p1.e(SourceFile:117)
	at v1.u.a(SourceFile:30)
	at w.e1.e(SourceFile:33)
	at v1.u.a(SourceFile:30)
	at k0.o5.a(SourceFile:25)
	at k0.o5.b(SourceFile:8)
	at ab.c.B(SourceFile:60)
	at y0.z.b(SourceFile:48)
	at y0.a0.c(SourceFile:153)
	at v1.m1.a(SourceFile:3)
	at v1.j0.o0(SourceFile:132)
	at v1.q0.b(SourceFile:44)
	at v1.q0.j(SourceFile:113)
	at v1.q0.g(SourceFile:90)
	at androidx.compose.ui.platform.AndroidComposeView.w(SourceFile:34)
	at v1.i1.a(SourceFile:4)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:14)
	at android.view.View.draw(View.java:23892)
	at android.view.View.updateDisplayListIfDirty(View.java:22756)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
	at android.view.View.updateDisplayListIfDirty(View.java:22712)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
	at android.view.View.updateDisplayListIfDirty(View.java:22712)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
	at android.view.View.updateDisplayListIfDirty(View.java:22712)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
	at android.view.View.updateDisplayListIfDirty(View.java:22712)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
	at android.view.View.updateDisplayListIfDirty(View.java:22712)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
	at android.view.View.updateDisplayListIfDirty(View.java:22712)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4939)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4643)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3822)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

**Comment by axiel7** [comment]
Could you try to reproduce the crash with the 1.2.3 beta? You can join Play Store beta or download the apk from the Discord server
