### ISSUE TITLE
crash when opening settings

### ISSUE THREAD

**Issue by whyakari** [axiel7/AniHyou-android#8]
**Describe the bug (required)**
> the bug is when I click on the settings gear and it crashes out of nowhere.

**To Reproduce**
1. Go to app 
2. Click on profile 
4. click on the profile gear above
5. See error: 
```
FATAL EXCEPTION: main
Process: com.axiel7.anihyou, PID: 28867
java.lang.NullPointerException
	at u8.e.d0(SourceFile:274)
	at t0.b.e(SourceFile:46)
	at t0.b.d0(SourceFile:9)
	at n.i.a(SourceFile:291)
	at n.i.f0(SourceFile:76)
	at t0.b.f0(SourceFile:54)
	at l0.q.J(SourceFile:346)
	at l0.q.O(SourceFile:81)
	at l0.q.s(SourceFile:172)
	at l0.q.H(SourceFile:27)
	at l0.w.y(SourceFile:22)
	at l0.h2.s(SourceFile:87)
	at l0.e2.l0(SourceFile:389)
	at androidx.compose.ui.platform.e1.doFrame(SourceFile:7)
	at androidx.compose.ui.platform.c1.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7933)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
	Suppressed: za.g: [l0.m1@392c7ac, androidx.compose.ui.platform.d2@95d9c75, w1{Cancelling}@a05740a, d1@769a47b]
```

**Expected behavior**
> open the settings tab, where there are options to change the application's color mode to dark mode, for example.

**Screenshots**
> ![Screenshot_20230904-005919](https://github.com/axiel7/AniHyou-android/assets/58480908/07202e09-7b53-4017-a0e1-486fce6a153e)
> detail: when I click there, the application freezes and closes.

**Enviroment (required)**
 - Device model: Xiaomi Redmi Note 8
 - Android version: Android 13
 - App version: 1.1.6

**Additional context**

**Comment by axiel7** [comment]
I think this is caused by an old setting option incompatible with the new version. Try clearing app data and let me know if is still crashing

**Comment by whyakari** [comment]
> I think this is caused by an old setting option incompatible with the new version, but I can't say which one. Try clearing app data and let me know if is still crashing

It worked! thanks
